plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE
  - README.md
theme: jekyll-theme-dinky
title: Colin’s Weather Links
remote_theme: pages-themes/dinky@v0.1.2
google_analytics: G-P3QPP839NL
