plugins:
  - jekyll-relative-links
  - jekyll-readme-index
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE
  - README.md
theme: jekyll-theme-dinky
title: Colin’s Weather Links
